pipeline:
  test:
    image: golang:1.20
    commands:
      - make test
      
  build:
    image: golang:1.20
    commands:
      - make bin/vault-webhook-linux-amd64

  docker-branch:
    image: plugins/docker
    repo: quay.io/uswitch/vault-webhook
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
    when:
      event: push

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/vault-webhook
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    when:
      event: push
      branch: master

  docker-tagged:
    image: plugins/docker
    repo: quay.io/uswitch/vault-webhook
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
