apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databasecredentialbindings.vaultwebhook.uswitch.com
spec:
  group: vaultwebhook.uswitch.com
  version: v1alpha1
  names:
    kind: DatabaseCredentialBinding
    plural: databasecredentialbindings
    shortNames:
      - dcb
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            database:
              type: string
            role:
              type: string
