apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databasecredentialbindings.vaultwebhook.uswitch.com
spec:
  group: vaultwebhook.uswitch.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                database:
                  type: string
                role:
                  type: string
                outputPath:
                  type: string
                outputFile:
                  type: string
  names:
    kind: DatabaseCredentialBinding
    plural: databasecredentialbindings
    shortNames:
      - dcb
  scope: Namespaced
