// Code generated by lister-gen. DO NOT EDIT.

package v1

// DatabaseCredentialBindingListerExpansion allows custom methods to be added to
// DatabaseCredentialBindingLister.
type DatabaseCredentialBindingListerExpansion interface{}

// DatabaseCredentialBindingNamespaceListerExpansion allows custom methods to be added to
// DatabaseCredentialBindingNamespaceLister.
type DatabaseCredentialBindingNamespaceListerExpansion interface{}
