// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	vaultwebhookuswitchcomv1 "github.com/uswitch/vault-webhook/pkg/apis/vaultwebhook.uswitch.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDatabaseCredentialBindings implements DatabaseCredentialBindingInterface
type FakeDatabaseCredentialBindings struct {
	Fake *FakeVaultwebhookV1
	ns   string
}

var databasecredentialbindingsResource = schema.GroupVersionResource{Group: "vaultwebhook.uswitch.com", Version: "v1", Resource: "databasecredentialbindings"}

var databasecredentialbindingsKind = schema.GroupVersionKind{Group: "vaultwebhook.uswitch.com", Version: "v1", Kind: "DatabaseCredentialBinding"}

// Get takes name of the databaseCredentialBinding, and returns the corresponding databaseCredentialBinding object, and an error if there is any.
func (c *FakeDatabaseCredentialBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *vaultwebhookuswitchcomv1.DatabaseCredentialBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(databasecredentialbindingsResource, c.ns, name), &vaultwebhookuswitchcomv1.DatabaseCredentialBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vaultwebhookuswitchcomv1.DatabaseCredentialBinding), err
}

// List takes label and field selectors, and returns the list of DatabaseCredentialBindings that match those selectors.
func (c *FakeDatabaseCredentialBindings) List(ctx context.Context, opts v1.ListOptions) (result *vaultwebhookuswitchcomv1.DatabaseCredentialBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(databasecredentialbindingsResource, databasecredentialbindingsKind, c.ns, opts), &vaultwebhookuswitchcomv1.DatabaseCredentialBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &vaultwebhookuswitchcomv1.DatabaseCredentialBindingList{ListMeta: obj.(*vaultwebhookuswitchcomv1.DatabaseCredentialBindingList).ListMeta}
	for _, item := range obj.(*vaultwebhookuswitchcomv1.DatabaseCredentialBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested databaseCredentialBindings.
func (c *FakeDatabaseCredentialBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(databasecredentialbindingsResource, c.ns, opts))

}

// Create takes the representation of a databaseCredentialBinding and creates it.  Returns the server's representation of the databaseCredentialBinding, and an error, if there is any.
func (c *FakeDatabaseCredentialBindings) Create(ctx context.Context, databaseCredentialBinding *vaultwebhookuswitchcomv1.DatabaseCredentialBinding, opts v1.CreateOptions) (result *vaultwebhookuswitchcomv1.DatabaseCredentialBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(databasecredentialbindingsResource, c.ns, databaseCredentialBinding), &vaultwebhookuswitchcomv1.DatabaseCredentialBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vaultwebhookuswitchcomv1.DatabaseCredentialBinding), err
}

// Update takes the representation of a databaseCredentialBinding and updates it. Returns the server's representation of the databaseCredentialBinding, and an error, if there is any.
func (c *FakeDatabaseCredentialBindings) Update(ctx context.Context, databaseCredentialBinding *vaultwebhookuswitchcomv1.DatabaseCredentialBinding, opts v1.UpdateOptions) (result *vaultwebhookuswitchcomv1.DatabaseCredentialBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(databasecredentialbindingsResource, c.ns, databaseCredentialBinding), &vaultwebhookuswitchcomv1.DatabaseCredentialBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vaultwebhookuswitchcomv1.DatabaseCredentialBinding), err
}

// Delete takes name of the databaseCredentialBinding and deletes it. Returns an error if one occurs.
func (c *FakeDatabaseCredentialBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(databasecredentialbindingsResource, c.ns, name, opts), &vaultwebhookuswitchcomv1.DatabaseCredentialBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDatabaseCredentialBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(databasecredentialbindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &vaultwebhookuswitchcomv1.DatabaseCredentialBindingList{})
	return err
}

// Patch applies the patch and returns the patched databaseCredentialBinding.
func (c *FakeDatabaseCredentialBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vaultwebhookuswitchcomv1.DatabaseCredentialBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(databasecredentialbindingsResource, c.ns, name, pt, data, subresources...), &vaultwebhookuswitchcomv1.DatabaseCredentialBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*vaultwebhookuswitchcomv1.DatabaseCredentialBinding), err
}
