// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	vaultwebhookuswitchcomv1 "github.com/uswitch/vault-webhook/pkg/apis/vaultwebhook.uswitch.com/v1"
	versioned "github.com/uswitch/vault-webhook/pkg/client/clientset/versioned"
	internalinterfaces "github.com/uswitch/vault-webhook/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/uswitch/vault-webhook/pkg/client/listers/vaultwebhook.uswitch.com/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DatabaseCredentialBindingInformer provides access to a shared informer and lister for
// DatabaseCredentialBindings.
type DatabaseCredentialBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DatabaseCredentialBindingLister
}

type databaseCredentialBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDatabaseCredentialBindingInformer constructs a new informer for DatabaseCredentialBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDatabaseCredentialBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDatabaseCredentialBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDatabaseCredentialBindingInformer constructs a new informer for DatabaseCredentialBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDatabaseCredentialBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VaultwebhookV1().DatabaseCredentialBindings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VaultwebhookV1().DatabaseCredentialBindings(namespace).Watch(context.TODO(), options)
			},
		},
		&vaultwebhookuswitchcomv1.DatabaseCredentialBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *databaseCredentialBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDatabaseCredentialBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *databaseCredentialBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vaultwebhookuswitchcomv1.DatabaseCredentialBinding{}, f.defaultInformer)
}

func (f *databaseCredentialBindingInformer) Lister() v1.DatabaseCredentialBindingLister {
	return v1.NewDatabaseCredentialBindingLister(f.Informer().GetIndexer())
}
